# Generated by Django 3.2.7 on 2021-10-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=100)),
                ('userAge', models.IntegerField(default=0)),
                ('userWeight', models.IntegerField(default=0)),
                ('userHeight', models.IntegerField(default=0)),
                ('userDia', models.CharField(default='X', max_length=3)),
                ('userHyper', models.CharField(default='X', max_length=3)),
                ('userDysl', models.CharField(default='X', max_length=3)),
            ],
        ),
    ]
